### ISSUE TITLE
Use cases to update data ?

### ISSUE THREAD

**Issue by dag-io** [Karumi/KataSuperHeroesIOS#3]
Hola

Would use cases be appropriate to update data ? Let's say for example **AddSuperHeroe**. Or is there a better way to handle this ?

Cheers

**Comment by pedrovgs** [comment]
Hi @dag-io!

That's the way to go. The use cases should expose openly what a developer can do with your software. In this case, add a super hero should be a use case.

Is this the answer to your question?

**Comment by dag-io** [comment]
Yes. Thanks !

**Comment by pedrovgs** [comment]
You are welcome!
